[client]
# Set the default character set for the MySQL client
default-character-set=utf8

[mysqld]
server_id=4
log-bin=slave-bin
binlog-format=ROW
# Ignore the 'mysql' database from being backed up
binlog-ignore-db=mysql

# Set to skip password authentication
# skip-grant-tables
# Set the port to 3306
port = 3308
# Set the MySQL installation directory
basedir=C:\\MySQL\\slave1  
# Set the directory for storing MySQL database data, MySQL 8+ does not require this configuration as the system will generate it automatically, otherwise an error might occur
datadir=C:\\MySQL\\slave1\\data
# Allow maximum number of connections
max_connections=20
# Set the character set used by the server to UTF-8 and avoid using Latin1 encoding
character-set-server=utf8
# Set the default storage engine to be used when creating tables
default-storage-engine=INNODB

sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION
